# -*- coding: utf-8 -*-
"""import_IPEA_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GEXnDzlZZw8UpUd2lrZtVPmRno_Jts3

Script  to download data from IPA data
https://pypi.org/project/ipeadatapy/#description
https://www.luanborelli.net/ipeadatapy/docs/usage/functions.html

Arrecadação das receitas federais - receita bruta
Frequência: Mensal de 1993.01 até 2023.11
Fonte: Ministério da Economia, Secretaria da Receita Federal (Min. Economia/SRF)
Unidade: R$ (milhões)
Comentário: Soma das receitas administradas pela Receita Federal com as receitas administradas por outros órgãos. Mais informações: https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/dados-abertos/receitadata/arrecadacao/a>.
Atualizado em: 30/12/2023
"""

import ipeadatapy
import pandas as pd
import useful_functions

ipeadatapy.list_series()

series_list = ipeadatapy.list_series()
filtered_list = series_list[series_list['NAME'].str.contains('Arrecadação das receitas federais - receita bruta', case=False)]

# Find the code for the desired list
desired_code = filtered_list['CODE'].values[0]

# Initial date
initial_year = '2001'

# Get the data
df_revenue_raw = ipeadatapy.timeseries(series = desired_code)

# Copy the dataframe
df_revenue = df_revenue_raw.copy()


# Filter the data to start from the initial year
df_revenue = df_revenue[df_revenue.index >= initial_year]

# Format index to month and year
df_revenue.index = df_revenue.index.strftime('%m-%Y')

# Filter only the desired column
df_revenue = df_revenue[['VALUE (R$)']].astype(float)

# Rename the column
df_revenue.rename(columns={'VALUE (R$)': 'eco_total_revenue'}, inplace=True)

# rename index
df_revenue.index.names = ['date']

# Convert the dataframe to monthly
df_revenue = useful_functions.convert_df_to_monthly(df_revenue, '%m-%Y')

# Save the dataframe to a csv file
df_revenue.to_csv('../data/df_total_revenue.csv')